name: Sync upstream

on:
  schedule:
    # 06:00 UTC+8
    - cron: '0 22 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch upstream
        run: |
          git clone --bare \
            https://gitlab.inria.fr/core-math/core-math.git \
            upstream.git

      - name: Update sync branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          target_url="https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git --git-dir=upstream.git push --force \
            "$target_url" HEAD:sync
